language: cpp
compiler:
  - gcc
os:
  - linux
  - osx
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgconf-2-4
services:
  - docker
  - xvfb
env:
  matrix:
    - NODE_NVM_VERSION="6.14.1"
    - NODE_NVM_VERSION="7.10.1"
    - NODE_NVM_VERSION="8.11.1"
    - NODE_NVM_VERSION="9.11.1"
    - NODE_NVM_VERSION="10.8.0"
    - NODE_NVM_VERSION="11.2.0"
    - NODE_NVM_VERSION="12.0.0"
    - NODE_NVM_VERSION="13.0.0"
    - NODE_NVM_VERSION="14.0.0"
    - ELECTRON_VERSION="2.0.7" ELECTRON_MOCHA=true MOCHA_RUNTIME_VERSION="8"
    - ELECTRON_VERSION="3.0.10" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="3.1.11" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="4.0.8" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="4.1.5" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="4.2.8" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="5.0.9" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="6.0.2" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="6.1.10" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="7.1.14" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="7.2.4" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="7.3.3" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="8.0.3" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="8.1.1" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="8.2.5" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="8.3.4" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="8.4.1" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="8.5.2" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="9.0.0" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="9.1.2" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="9.2.0" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="9.3.2" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="10.0.0" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="10.1.3" ELECTRON_MOCHA=true
    - ELECTRON_VERSION="11.0.0" ELECTRON_MOCHA=true
    - MUSL=true NODE_NVM_VERSION="9.11.1"
    - MUSL=true NODE_NVM_VERSION="10.8.0"
    - MUSL=true NODE_NVM_VERSION="11.2.0"
    - MUSL=true NODE_NVM_VERSION="12.0.0"
    - MUSL=true NODE_NVM_VERSION="13.0.0"
    - MUSL=true NODE_NVM_VERSION="14.0.0"
matrix:
  exclude:
    - os: osx
      env: MUSL=true NODE_NVM_VERSION="9.11.1"
    - os: osx
      env: MUSL=true NODE_NVM_VERSION="10.8.0"
    - os: osx
      env: MUSL=true NODE_NVM_VERSION="11.2.0"
    - os: osx
      env: MUSL=true NODE_NVM_VERSION="12.0.0"
    - os: osx
      env: MUSL=true NODE_NVM_VERSION="13.0.0"
    - os: osx
      env: MUSL=true NODE_NVM_VERSION="14.0.0"
    - os: linux
      env: ELECTRON_VERSION="2.0.7" ELECTRON_MOCHA=true MOCHA_RUNTIME_VERSION="8"
before_install:
  - if [[ $ELECTRON_VERSION ]]; then
    export npm_config_target=$ELECTRON_VERSION;
    export npm_config_target_arch=x64;
    export npm_config_disturl=https://atom.io/download/electron;
    export npm_config_runtime=electron;
    fi
  - if [[ $MUSL ]]; then
    EXTRA_NODE_PRE_GYP_FLAGS="--target_libc=musl";
    fi;
  - git clone https://github.com/creationix/nvm.git ../.nvm && source ../.nvm/nvm.sh
  - NODE_NVM_VERSION="${NODE_NVM_VERSION:=11.2.0}"
  - nvm install $NODE_NVM_VERSION
  - nvm use $NODE_NVM_VERSION
  - node --version
  - npm --version
  - $CXX --version
install:
  - if [[ $MUSL ]]; then
    scripts/alpine-build.sh;
    else
    npm install --build-from-source;
    fi
before_script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export DISPLAY=:99.0; fi
script:
  - if [[ $MUSL ]]; then
    scripts/alpine-test.sh ./node_modules/.bin/node-pre-gyp package testpackage $EXTRA_NODE_PRE_GYP_FLAGS;
    elif [[ $ELECTRON_MOCHA ]]; then
    scripts/electron-mocha-test.sh ./node_modules/.bin/node-pre-gyp package testpackage $EXTRA_NODE_PRE_GYP_FLAGS;
    else
    ./node_modules/.bin/node-pre-gyp package testpackage $EXTRA_NODE_PRE_GYP_FLAGS;
    npm test;
    fi
before_deploy:
  - npm run package --verbose
deploy:
  provider: releases
  api_key:
    secure: X+W8B96JKhIcCrOvVCo0k9ZRcgMYJ+3bSWp5weAzLXp3InENXQMh0VlgKmMWJJtneu4x0XdJLdpjwXmYoKiKr5YBC5nqekySF0SNfa3gebQpXNpyCTfofIVKlzlqFQMTmn6bmcfg+cfZMNII/BExxc1+CRPq9vxotN7Dl+gJHvE3uTLO2VDtmo2LmdRUmVsryR5XVjcj8V9mNRIidE+CAZ18E7ZJa8QChLwua/RzgMiXJz0kA+yVPw+01MymmlcoEn92z1KN033W3JVDkkBjNi/jUeMq87tlBVBdKbKq2sUhKdUG7mKLielbLm0fgg9gnNdzHqL2wcV2IYkdJZZwxM4CMdbAvUoZqNzwc3vk0sjQ3jYbO2SCvY42nGEXif2YwkqhDPCRYx85vv4ONB7d464fafE7mF5jpDOzMvtfH/s2PF98Aw5UVirwMg1nWvUDuxBzqAebjrAbF17lLlMNJ1ZCsxe0WA7O79N3k1n3/91J3yonDluGbiP2qh/6YHVLH0AEuJyAYU8HGSLtnRrN91h70S65YNnPrZkxZ0vrK/QfarE89KhIBHIQlNfXlYf7cS4LaurGZjQmVf8Eb1LNupTmk/9U8T0jIb79/L01fRegrvHXnx3wwRaXGjjiqNMPkHhxpzmQY12wD3jT1F+Kc7efnoGQ9/GQCHSOVXf9YDg=
  file: $TRAVIS_BUILD_DIR/build/stage/julianhille/MuhammaraJS/releases/download/**/*.gz
  file_glob: true
  on:
    tags: true
    repo: julianhille/MuhammaraJS
  skip_cleanup: 'true'
